# Generated by Django 2.2 on 2019-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank='False', max_length=50, null='False')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(blank='False', max_length=100)),
                ('age', models.IntegerField()),
                ('e_mail', models.CharField(blank='False', max_length=50)),
                ('number_phone', models.IntegerField(blank='False', null='True')),
                ('github', models.CharField(max_length=50)),
                ('Student_Mentor', models.BooleanField()),
            ],
        ),
    ]
