# Generated by Django 2.2 on 2019-06-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Mentor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Program')),
                ('studentA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student2')),
            ],
        ),
    ]
