# Generated by Django 2.2 on 2019-06-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_students_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_mentor',
            name='studentA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Student2'),
        ),
    ]
