# Generated by Django 2.2 on 2019-06-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_course_courses_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='team_students',
            field=models.ManyToManyField(through='user.Students_Mentor', to='user.Student2'),
        ),
        migrations.AlterField(
            model_name='students_mentor',
            name='studentA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student2'),
        ),
    ]
