# Generated by Django 2.2 on 2019-06-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190605_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
