# Generated by Django 2.2 on 2019-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190605_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Student_Mentor',
            field=models.BooleanField(default=True),
        ),
    ]
