# Generated by Django 2.2 on 2019-06-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190620_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='age',
            field=models.IntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='github',
            field=models.CharField(max_length=50, null='True'),
        ),
    ]
